apiVersion: v1
kind: Template
metadata:
  name: builder-all-template
  annotations:
    description: "Template for SpringBoot apps creation. Creates OSE objects: bc, dc, route & service"
    tags: "springboot"
    iconClass: icon-java
  
objects:

- apiVersion: v1
  kind: Route
  metadata:
    creationTimestamp: null
    name: ${APPLICATION_NAME}-route
  spec:
    to:
      kind: Service
      name: ${APPLICATION_NAME}-service

- apiVersion: v1
  kind: Service
  metadata:
    name: ${APPLICATION_NAME}-service
  spec:
    ports:
    - name: web
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      deploymentconfig: ${APPLICATION_NAME}-dc
    type: ClusterIP

- apiVersion: v1
  kind: ImageStream
  metadata:
    name: ${APPLICATION_NAME}-is
   
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: ${APPLICATION_NAME}-bc
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${APPLICATION_NAME}-is:latest
    source:
      git:
        ref: ${SOURCE_REPOSITORY_BRANCH}
        uri: ${SOURCE_REPOSITORY_URL}
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: openshift-springboot-s2i:latest
      type: Source
    triggers:
    - imageChange: {}
      type: ImageChange
    - type: ConfigChange

- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: ${APPLICATION_NAME}-dc
  spec:
    template: 
      metadata:
        labels:
          name: ${APPLICATION_NAME}-dc
      spec:
        containers:
          - name: ${APPLICATION_NAME}
    replicas: 1 
    selector:
      name: ${APPLICATION_NAME}-dc
    triggers:
      - type: "ConfigChange" 
      - type: "ImageChange" 
        imageChangeParams:
          automatic: true
          containerNames:
            - ${APPLICATION_NAME}
          from:
            kind: "ImageStreamTag"
            name: ${APPLICATION_NAME}-is:latest

parameters:
  - name: APPLICATION_NAME 
    description: "The name of application"
    value: "prime-numbers"
    required: true 
  - name: SOURCE_REPOSITORY_URL 
    description: "The URL of the repository with your application source code"
    value: "https://github.com/veretie/prime-numbers.git"
    required: true 
  - name: SOURCE_REPOSITORY_BRANCH
    description: "Git branch"
    value: "develop"
    required: true 	


